config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations], controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  namespace :admin, path: 'admin' do
    resources :users
    resources :users, only: :index do
      member do
        patch :toggle_admin_role
      end
    end
    resources :departments
    resources :semesters
    get '/', to: 'users#index'
  end

  namespace :hod, path: 'hod' do
    resources :users
    resources :subjects
    resources :faculty_subjects
    resources :faculty_subjects, only: :index do
      member do
        get :get_subject
      end
    end
    resources :lectures
    resources :time_tables
    get '/', to: 'users#index'
  end

  namespace :faculty, path: 'faculty' do
    resources :users
    resources :lectures
    resources :attendances
    get '/', to: 'users#index'
  end

  namespace :student, path: 'student' do
    resources :lectures
    resources :attendances
    resources :details
    resources :marks
    resources :assignments
    get '/', to: 'details#index'
  end
end

app/models/department.rb
# == Schema Information
#
# Table name: departments
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  code       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Department < ApplicationRecord
  has_many :users
  has_many :subjects
  has_many :semesters
  accepts_nested_attributes_for :semesters, reject_if: :all_blank, allow_destroy: true
  has_one :hod, -> { where(hod: 'true') }, class_name: "User", foreign_key: "hod_department_id"

  def self.departments_without_hod
    self.select { |u| !u.hod }
  end
end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < Admin::MainController
  before_action :get_department, only: [:edit, :update, :destroy]

  def index
    @departments = Department.all
  end

  def create
    @department = Department.new(department_params)
    @department.save
    redirect_to admin_departments_url, notice: 'Department added successfully'
  end

  def edit; end

  def new
    @department = Department.new
    @department.semesters.build
  end

  def show; end

  def destroy
    if @department.destroy
      redirect_to admin_departments_url, notice: 'Department deleted successfully'
    else
      redirect_to admin_departments_url, alert: 'Try again!!!'
    end
  end

  def update
    if @department.update(department_params)
      redirect_to admin_departments_url, notice: 'Department updated successfully'
    else
      render action: 'edit', alert: 'Try again!!!'
    end
  end

  private

  def department_params
    params.require(:department).permit(:name, :code, semesters_attributes: [:id, :name, :done, :_destroy])
  end

  def get_department
    @department = Department.find(params[:id])
  end
end

app/helpers/admin/departments_helper.rb
module Admin::DepartmentsHelper
end

app/views/admin/departments/_form.html.erb
<div class="main_container">
  <div class="inner">
    <div class="form_start">
      <%= form_for([:admin, @department]) do |f| %>
        <%= f.text_field :name, required: true , class: 'input_text', placeholder: 'Department Name'%><br/>
        <%= f.number_field :code, required: true , class: 'input_text', placeholder: 'Department Code'%><br/><br>
        <h5>Semesters</h5>
        <div id="semesters">
          <%= f.fields_for :semesters do |semester| %>
            <%= render 'semester_fields', f: semester %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Semester', f, :semesters %>
          </div>
        </div>
        <div class="submit_container">
          <%= f.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/departments/_semester_fields.html.erb
<div class="nested-fields">
  <%= f.text_field :name, required: true , class: 'input_text', placeholder: 'Semester Name'%>
  <%= link_to_remove_association "Remove Semester", f %>
</div>

app/views/admin/departments/edit.html.erb
<div class="heading_only">
  <span>Edit Department Details</span>
</div>
<%= render :partial => 'form' %>

app/views/admin/departments/index.html.erb
<div class="welcom_admin">
  <div class="welcom_admin_inner">
    <div class="heding_top">
      <span>All Departments</span>
      <%= link_to( 'Add new Department',new_admin_department_path ) %>
    </div>
    <div class="accordion" id="showDepartments">
      <% @departments.each_with_index do |department,index| %>
        <div class="card">
          <div class="card-header" id="<%= department.id %>">
            <h5 class="mb-0">
              <button class="btn btn-link left_btn" type="button" data-toggle="collapse" data-target="#hex_<%= index %>" aria-expanded="true" aria-controls="hex_<%= index %>">
                <%= department.name %>
              </button>
              <button class="btn btn-link btn_link_right" type="button">
                <%= link_to( 'Edit Department Details', edit_admin_department_path(department.id) ) %>
              </button>
              <button class="btn btn-link btn_link_right" type="button">
                <%= link_to( "Remove Department", admin_department_path(department.id), method: :delete, data: { confirm: "You sure to remove department? This cannot be undone." }) %>
              </button>
            </h5>
          </div>

          <div id="hex_<%= index %>" class="collapse" aria-labelledby="<%= department.id %>" data-parent="#showDepartments">
            <div class="card-body">
              <label>Code :</label>
              <span><%= department.code %></span><br>
              <label>HOD :</label>
              <span><%= department.hod.name %></span><br><br>
              <% if department.semesters.present? %>
                <label>Semesters :</label>
                <table class="table table-hover table-striped">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Name</th>
                      <th scope="col"></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% department.semesters.each_with_index do |semester,index| %>
                    <tr>
                      <th scope="row"><%= index+1 %></th>
                      <td><%= semester.name.capitalize %></td>
                      <td>
                        <%= link_to( "Remove", admin_semester_path(semester.id), method: :delete, data: { confirm: "You sure to remove semester? This cannot be undone." }) %>
                      </td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              <% else %>
                <h5>No Semester Added</h5>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/departments/new.html.erb
<div class="heading_only">
  <span>Add new Department</span>
</div>
<%= render :partial => 'form' %>