config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations], controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  namespace :admin, path: 'admin' do
    resources :users
    resources :users, only: :index do
      member do
        patch :toggle_admin_role
      end
    end
    resources :departments
    resources :semesters
    get '/', to: 'users#index'
  end

  namespace :hod, path: 'hod' do
    resources :users
    resources :subjects
    resources :faculty_subjects
    resources :faculty_subjects, only: :index do
      member do
        get :get_subject
      end
    end
    resources :lectures
    resources :time_tables
    get '/', to: 'users#index'
  end

  namespace :faculty, path: 'faculty' do
    resources :users
    resources :lectures
    resources :attendances
    get '/', to: 'users#index'
  end

  namespace :student, path: 'student' do
    resources :lectures
    resources :attendances
    resources :details
    resources :marks
    resources :assignments
    get '/', to: 'details#index'
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :inet
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  hod                    :boolean          default(FALSE)
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :inet
#  name                   :string
#  phone                  :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :string
#  sign_in_count          :integer          default(0), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  department_id          :integer
#  hod_department_id      :integer
#  semester_id            :integer
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  ROLES = ['admin','faculty','student']
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, :trackable

  validates :role, inclusion: { in: ROLES, message: "%{value} is not a valid role!" }

  belongs_to :department, optional: true
  belongs_to :hod_department, class_name: "Department", foreign_key: "hod_department_id", optional: true
  belongs_to :semester, optional: true
  has_many :faculty_subjects, class_name: "FacultySubject", foreign_key: "faculty_id"
  has_many :subjects, through: :faculty_subjects, source: :user
  has_many :lectures, class_name: "Lecture", foreign_key: "faculty_id"
  has_many :student_lectures, class_name: "StudentLecture", foreign_key: "student_id"
  has_many :periods, through: :student_lectures, source: :user
  has_many :attendances, class_name: "Attendance", foreign_key: "user_id"

  # Methods -  user.admin?, user.faculty?, user.student?
  ROLES.each do |method|
    define_method "#{method}?" do
      role == method
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::MainController
  before_action :get_user, only: [:edit, :update, :destroy]

  def index
    @users = User.order('name asc').where(hod: true)
  end

  def create
    @user = User.new(user_params)
    @user.password = 'password'
    @user.role = 'faculty'
    @user.hod_department_id = @user.department_id
    @user.hod = true
    if @user.save
      flash[:notice] = 'HOD added successfully'
      redirect_to admin_users_path
    else
      flash[:error] = "Can't add HOD because #{@user.errors.full_messages.to_sentence.downcase}"
      render action: 'new'
    end
  end

  def edit; end

  def new
    @user = User.new
  end

  def show; end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: 'HOD removed successfully' 
    else
      redirect_to admin_users_path, info: 'Please try again'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: 'HOD details updated successfully'
    else
      render action: 'edit', info: 'Please try again'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :department_id)
  end

  def get_user
    @user = User.find(params[:id])
  end
end

app/controllers/faculty/users_controller.rb
class Faculty::UsersController < Faculty::MainController
  before_action :get_user, only: [:edit, :update, :destroy]

  def index
    @students = User.order('name asc').where("role = ? AND department_id = ?", 'student', current_user.department.id)
  end

  def create
    user = User.new(user_params)
    user.password = 'password'
    user.role = 'student'
    if user.save
      flash[:notice] = 'Student added successfully'
      redirect_to faculty_users_url
    else
      flash[:error] = 'Some error occurred'
      render action: 'new'
    end
  end

  def edit; end

  def new
    @user = User.new
  end

  def show; end

  def destroy
    if @user.destroy
      redirect_to faculty_users_url, notice: 'Student removed successfully' 
    else
      redirect_to faculty_users_url, info: 'Please try again'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to faculty_users_url, notice: 'Student details updated successfully'
    else
      render action: 'edit', info: 'Please try again'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :department_id)
  end

  def get_user
    @user = User.find(params[:id])
  end
end

app/controllers/hod/faculty_subjects_controller.rb
class Hod::FacultySubjectsController < Hod::MainController
  before_action :get_faculty_subject, only: [:edit, :update, :destroy]

  def index
    @faculty_subject = FacultySubject.where(department_id: current_user.department_id)
  end

  def create
    @faculty_subject = FacultySubject.new(faculty_subject_params)
    if @faculty_subject.save
      flash[:notice] = 'Faculty Subject Added Successfully'
      redirect_to hod_faculty_subjects_path(@faculty_subject)
    else
      flash[:error] = @faculty_subject.errors.full_messages.to_sentence
      render action: 'new'
    end
  end

  def edit; end

  def new
    @faculty_subject = FacultySubject.new
  end

  def show; end

  def destroy
    redirect_to hod_faculty_subjects_path, flash[:notice] = 'Faculty Subject deleted Successfully' if @faculty_subject.destroy
  end

  def update
    if @faculty_subject.update(faculty_subject_params)
      redirect_to hod_faculty_subjects_path, notice: 'Faculty Subject updated successfully'
    else
      flash[:error] = @faculty_subject.errors.full_messages.to_sentence
      render action: 'edit'
    end
  end

  private

  def faculty_subject_params
    params.require(:faculty_subject).permit(:faculty_id, :faculty_subject_id)
  end

  def get_faculty_subject
    @faculty_subject = FacultySubject.find(params[:id])
  end
end

app/controllers/hod/lectures_controller.rb
class Hod::LecturesController < Hod::MainController
end

app/controllers/hod/main_controller.rb
class Hod::MainController < ApplicationController
  include Hod::MainHelper

  before_action :authenticate_user!
  before_action :ensure_hod

  private

  def ensure_hod
    redirect_to root_path, alert: "You are not an HOD!!!" and return unless current_user.hod?
  end
end

app/controllers/hod/subjects_controller.rb
class Hod::SubjectsController < Hod::MainController
  before_action :get_subject, only: [:edit, :update, :destroy]

  def index
    @subjects = Subject.where(department_id: current_user.department_id)
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      flash[:notice] = 'Subject Added Successfully'
      redirect_to hod_subjects_path(@subject)
    else
      flash[:error] = @subject.errors.full_messages.to_sentence
      render action: 'new'
    end
  end

  def edit; end

  def new
    @subject = Subject.new
  end

  def show; end

  def destroy
    redirect_to hod_subjects_path, flash[:notice] = 'Subject deleted Successfully' if @subject.destroy
  end

  def update
    if @subject.update(subject_params)
      redirect_to hod_subjects_path, notice: 'Subject updated successfully'
    else
      flash[:error] = @subject.errors.full_messages.to_sentence
      render action: 'edit'
    end
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :code, :semester_id)
  end

  def get_subject
    @subject = Subject.find(params[:id])
  end
end

app/controllers/hod/time_tables_controller.rb
class Hod::TimeTablesController < Hod::MainController
  before_action :get_time_table, only: [:edit, :update, :destroy]

  def index
    @time_tables = TimeTable.all
    @lectures = Lecture.all
  end

  def create
    time_table = TimeTable.new(time_table_params)
    if time_table.save
      flash[:notice] = 'Time Table Created successfully'
      redirect_to hod_time_tables_path
    else
      flash[:error] = time_table.errors.full_messages.to_sentence
      render action: 'new'
    end
  end

  def edit; end

  def new
    @time_table = TimeTable.new
  end

  def show; end

  def destroy
    redirect_to hod_time_tables_path, notice: 'Time Table deleted successfully' if @time_table.destroy
  end

  def update
    if @time_table.update(time_table_params)
      flash[:notice] = 'Time Table updated successfully'
      redirect_to hod_time_tables_path
    else
      flash[:error] = @time_table.errors.full_messages.to_sentence
      render action: "edit"
    end
  end

  private

  def time_table_params
    params.require(:time_table).permit(:faculty_id, :faculty_subject_id)
  end

  def time_table
    @time_table = TimeTable.find(params[:id])
  end
end

app/controllers/hod/users_controller.rb
class Hod::UsersController < Hod::MainController
  before_action :get_user, only: [:edit, :update, :destroy, :show]

  def index
    @faculties = User.order('name asc').where("id != ?", current_user.id).where("role = ? AND department_id = ?", 'faculty', current_user.department.id)
    @students = User.order('name asc').where("role = ? AND department_id = ?", 'student', current_user.department.id)
  end

  def create
    user = User.new(user_params)
    user.password = 'password'
    user.department = current_user.department
    user.save
    redirect_to hod_users_url, notice: 'HOD added successfully'
  end

  def edit; end

  def new
    @user = User.new
  end

  def show; end

  def destroy
    redirect_to hod_users_url, notice: 'HOD removed' if @user.destroy
  end

  def update
    if @user.update(user_params)
      redirect_to hod_users_url, notice: 'HOD details updated successfully'
    else
      render action: 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :role, :semester_id)
  end

  def get_user
    @user = User.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
  before_action :ensure_confirmed, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end

  def ensure_confirmed
    user = User.find_by(email: params[:user][:email])
    unless user.present? && user.confirmed?
      redirect_to root_path, alert: 'Please confirm your account before Sign In'
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/faculty/users_helper.rb
module Faculty::UsersHelper
end

app/helpers/hod/faculty_subjects_helper.rb
module Hod::FacultySubjectsHelper
end

app/helpers/hod/lectures_helper.rb
module Hod::LecturesHelper
end

app/helpers/hod/main_helper.rb
module Hod::MainHelper
end

app/views/hod/users/_faculties.html.erb
<% if faculties.present? %> 
  <h5>All Faculties:</h5>
  <table class="table table-hover table-striped" id="faculty_table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Department</th>
        <th scope="col">Confirmed</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% faculties.each_with_index do |faculty,index| %>
      <tr>
        <th scope="row"><%= index+1 %></th>
        <td><%= faculty.name.capitalize %></td>
        <td><%= faculty.email %></td>
        <td><%= faculty.department.name.capitalize %></td>
        <td><%= faculty.confirmed? ? 'Already Confirmed' : 'Confirmation Pending' %></td>
        <td><%= link_to( 'Edit', edit_hod_user_path(faculty.id) ) %></td>
        <td>
          <%= link_to( "Delete", hod_user_path(faculty.id), method: :delete, data: { confirm: "You sure to remove faculty? This cannot be undone." }) %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h5>There is no faculty in your department</h5>
<% end %>

app/views/hod/users/_form.html.erb
<div class="main_container">
  <div class="inner">
    <div class="form_start">
      <%= form_for([:hod, @user]) do |f| %>
        <%= f.text_field :name, required: true , class: 'input_text', placeholder: 'Name'%><br/>
        <%= f.email_field :email, required: true , class: 'input_text', placeholder: 'Email'%><br/>
        <%= f.select :role, options_for_select([['Faculty','faculty'],['Student','student']]), { :include_blank => 'Please Select Role' }, :required => true %>
        <%= f.select :semester_id, options_for_select(current_user.department.semesters.pluck(:name, :id), @user&.semester_id), { :include_blank => 'Please Select Semester' } %><br/>
        <br/>
        <div class="submit_container">
          <%= f.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/hod/users/_students.html.erb
<% if @students.present? %>
  <h5>All Students:</h5>
  <table class="table table-hover table-striped" id="student_table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Department</th>
        <th scope="col">Confirmed</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @students.each_with_index do |student,index| %>
      <tr>
        <th scope="row"><%= index+1 %></th>
        <td><%= student.name.capitalize %></td>
        <td><%= student.email %></td>
        <td><%= student.department.name.capitalize %></td>
        <td><%= student.confirmed? ? 'Already Confirmed' : 'Confirmation Pending' %></td>
        <td><%= link_to( 'Edit', edit_hod_user_path(student.id) ) %></td>
        <td>
          <%= link_to( "Delete", hod_user_path(student.id), method: :delete, data: { confirm: "You sure to remove student? This cannot be undone." }) %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h5>There is no student in your department</h5>
<% end %>

app/views/hod/users/edit.html.erb
<div class="heading_only">
  <span>Edit User</span>
</div>
<%= render :partial => 'form' %>

app/views/hod/users/index.html.erb
<div class="welcom_admin">
  <div class="welcom_admin_inner">
    <div class="heding_top">
      <span>Faculties and Students</span>
      <%= link_to( 'Add new User',new_hod_user_path ) %>
    </div>
    <% if params[:type].eql?('faculty') %>
      <%= render 'faculties', faculties: @faculties %>
    <% elsif params[:type].eql?('student') %>
      <%= render 'students', students: @students %>
    <% else %>
      <%= render 'faculties', faculties: @faculties %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $("#faculty_table").dataTable();
  });

  $(document).ready(function() {
    $("#student_table").dataTable();
  });
</script>

app/views/hod/users/new.html.erb
<div class="heading_only">
  <span>Create new User</span>
</div>
<%= render :partial => 'form' %>

app/views/hod/users/show.html.erb
<div class="welcom_admin">
  <div class="welcom_admin_inner">
    <div class="heding_top">
      <span><%= @user.name %></span>
    </div>
    <div class="accordion" id="showUsers">
      <div class="card">
        <div class="card-header" id="<%= @user.id %>">
          <h5 class="mb-0">
            <button class="btn btn-link left_btn" type="button" data-toggle="collapse" data-target="#hex_one" aria-expanded="true" aria-controls="hex_one">
              Click Here For Details
            </button>
            <button class="btn btn-link btn_link_right" type="button">
              <%= link_to( 'Edit', edit_user_path(@user.id) ) %>
            </button>
            <button class="btn btn-link btn_link_right" type="button">
              <%= link_to( "Destroy", user_path(@user.id), method: :delete, data: { confirm: "You sure to delete user? This cannot be undone." }) %>
            </button>
          </h5>
        </div>

        <div id="hex_one" class="collapse" aria-labelledby="<%= @user.id %>" data-parent="#showUsers">
          <div class="card-body">
            <label>Email :</label>
            <span><%= @user.email %></span><br>
            <label>Role :</label>
            <span><%= @user.role.name.capitalize %></span><br>
            <% if @user.department.present? %>
              <label>Department :</label>
              <span><%= @user.department.name.upcase %></span><br>
            <% end %>
            <% if @user.semester.present? %>
              <label>Semester :</label>
              <span><%= @user.semester.name.capitalize %></span><br>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>