config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations], controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  namespace :admin, path: 'admin' do
    resources :users
    resources :users, only: :index do
      member do
        patch :toggle_admin_role
      end
    end
    resources :departments
    resources :semesters
    get '/', to: 'users#index'
  end

  namespace :hod, path: 'hod' do
    resources :users
    resources :subjects
    resources :faculty_subjects
    resources :faculty_subjects, only: :index do
      member do
        get :get_subject
      end
    end
    resources :lectures
    resources :time_tables
    get '/', to: 'users#index'
  end

  namespace :faculty, path: 'faculty' do
    resources :users
    resources :lectures
    resources :attendances
    get '/', to: 'users#index'
  end

  namespace :student, path: 'student' do
    resources :lectures
    resources :attendances
    resources :details
    resources :marks
    resources :assignments
    get '/', to: 'details#index'
  end
end

app/models/lecture.rb
# == Schema Information
#
# Table name: lectures
#
#  id                 :bigint(8)        not null, primary key
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  faculty_id         :integer
#  faculty_subject_id :integer
#  time_table_id      :integer
#

class Lecture < ApplicationRecord
  belongs_to :faculty_subject
  belongs_to :faculty, -> { where(role: 'faculty') }, class_name: "User", foreign_key: "faculty_id"
  belongs_to :time_table, optional: true
  has_many :student_lectures, class_name: "StudentLecture", foreign_key: "lecture_id"
  has_many :students, through: :student_lectures
end

app/controllers/faculty/attendances_controller.rb
class Faculty::AttendancesController < Faculty::MainController
  skip_before_action :verify_authenticity_token, only: [:update]
  before_action :get_student, only: [:update]

  def index
    @students = User.where(role: 'student').where(department_id: current_user.department_id)
  end

  def update
    attendances = @user.attendances.where("DATE(created_at) = ?", Date.today)
    if attendances.blank?
      attendance = Attendance.new(present: true, user_id: @user.id, lecture_id: 1)
      attendance.save
      render json: {present: true}
    elsif attendances.first[:present] == false
      attendances.first[:present] = true
      attendances.first.save
      render json: {present: true}
    else
      attendances.first[:present] = false
      attendances.first.save
      render json: {present: false}
    end
  end

  private

  def get_student
    @user ||= User.find(params[:id])
  end
end

app/controllers/faculty/lectures_controller.rb
class Faculty::LecturesController < Faculty::MainController
  before_action :get_lecture, only: [:edit, :update, :destroy]

  def index
    @lectures = Subject.all
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      flash[:notice] = 'Subject Added Successfully'
      redirect_to hod_subjects_path(@subject)
    else
      flash[:error] = @subject.errors.full_messages.to_sentence
      render action: 'new'
    end
  end

  def edit; end

  def new
    @subject = Subject.new
  end

  def show; end

  def destroy
    redirect_to hod_subjects_path, flash[:notice] = 'Subject deleted Successfully' if @subject.destroy
  end

  def update
    if @subject.update(subject_params)
      redirect_to hod_subjects_path, notice: 'Subject updated successfully'
    else
      flash[:error] = @subject.errors.full_messages.to_sentence
      render action: 'edit'
    end
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :code, :semester_id)
  end

  def get_subject
    @subject = Subject.find(params[:id])
  end
end

app/controllers/faculty/main_controller.rb
class Faculty::MainController < ApplicationController
  include Faculty::MainHelper

  before_action :authenticate_user!
  before_action :ensure_faculty

  private

  def ensure_faculty
    redirect_to root_path, alert: "You are not a faculty!!!" and return unless current_user.faculty?
  end
end

app/controllers/faculty/users_controller.rb
class Faculty::UsersController < Faculty::MainController
  before_action :get_user, only: [:edit, :update, :destroy]

  def index
    @students = User.order('name asc').where("role = ? AND department_id = ?", 'student', current_user.department.id)
  end

  def create
    user = User.new(user_params)
    user.password = 'password'
    user.role = 'student'
    if user.save
      flash[:notice] = 'Student added successfully'
      redirect_to faculty_users_url
    else
      flash[:error] = 'Some error occurred'
      render action: 'new'
    end
  end

  def edit; end

  def new
    @user = User.new
  end

  def show; end

  def destroy
    if @user.destroy
      redirect_to faculty_users_url, notice: 'Student removed successfully' 
    else
      redirect_to faculty_users_url, info: 'Please try again'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to faculty_users_url, notice: 'Student details updated successfully'
    else
      render action: 'edit', info: 'Please try again'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :department_id)
  end

  def get_user
    @user = User.find(params[:id])
  end
end

app/controllers/hod/lectures_controller.rb
class Hod::LecturesController < Hod::MainController
end

app/controllers/student/lectures_controller.rb
class Student::LecturesController < Student::MainController
end

app/helpers/faculty/attendances_helper.rb
module Faculty::AttendancesHelper
end

app/helpers/faculty/lectures_helper.rb
module Faculty::LecturesHelper
end

app/helpers/faculty/main_helper.rb
module Faculty::MainHelper
end

app/helpers/faculty/users_helper.rb
module Faculty::UsersHelper
end

app/helpers/hod/lectures_helper.rb
module Hod::LecturesHelper
end

app/helpers/student/lectures_helper.rb
module Student::LecturesHelper
end

app/views/faculty/lectures/_form.html.erb
<div class="main_container">
  <div class="inner">
    <div class="form_start">
      <%= form_for @lecture do |f| %>
        <%= f.select :faculty_id, options_for_select(Role.find_by(name: "faculty").users.order(:name).map{|s|[s.name, s.id]}), { :include_blank => 'Please Select Faculty' }, :required => true %><br/>
        <%= f.select :faculty_subject_id, options_for_select(FacultySubject.all.map{|s|[s.subject.name, s.id]}), { :include_blank => 'Please Select Subject' }, :required => true %><br/><br>
        <div class="submit_container">
          <%= f.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  function get_subject(faculty_id){
    $.get("/get_subject", {faculty_id: faculty_id}, function(data){
      var $subject = $('#lecture_faculty_subject_id');
      $subject.empty();
      for (var i = 0; i < data.subjects.length; i++) {
        $subject.append('<option value='+data.subjects[i][1]+'>'+data.subjects[i][0]+'</option>');
      }
    }, "json");
  }

  $(document).ready(function () {
    $("#lecture_faculty_id").change(function () {
      var val = $(this).val();
      get_subject(val);
    });
  });
</script>

app/views/faculty/lectures/index.html.erb
<% if user_signed_in? && current_user.role.name == "hod" %>
  <div class="welcom_admin">
    <div class="welcom_admin_inner">
      <div class="heding_top">
        <span>Lectures Index</span>
        <%= link_to( 'Assign Lecture',new_lecture_path ) %>
      </div>
      <% if @lectures.present? %>
        <table class="table table-hover table-striped">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Lecture</th>
              <th scope="col">Faculty</th>
              <th scope="col">Subject</th>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% @lectures.each_with_index do |lecture,index| %>
            <tr>
              <th scope="row"><%= index+1 %></th>
              <td><%= lecture.id %></td>
              <td><%= lecture.faculty.name %></td>
              <td><%= lecture.faculty_subject.subject.name %></td>
              <td><%= link_to( 'Edit', edit_lecture_path(lecture.id) ) %></td>
              <td><%= link_to( "Delete", lecture_path(lecture.id), method: :delete, data: { confirm: "You sure to delete lecture? This cannot be undone." }) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <h3>No Lectures to show</h3>
      <% end %>
    </div>
  </div>
<% end %>